In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [2]:
df_mapping = pd.read_excel("Dashboard Master.xlsx",sheet_name="Origami - Amazon")
df_amazon_scrapped = pd.read_excel("Live_origami_amazon_hygeine_11_march.xlsx")

In [3]:
df_mapping.head()

,Category,Sub-category,Range,SKU,ASIN,Generic Title,Sales Tracking,Hygiene Tracking,MRP,Price Rule,Coupon Rule,SNS Rule,BXGY Rule,Buy Box Rule,Deal Tag Rule
0,Tissues,Toilet Tissues,Normal Range,ORG-TT-NR-P6-960-HB,B00E3QVP06,"Toilet Tissue Paper Roll, Pack of 6, 160 Pulls...",Yes,Yes,290,246.5,Yes,Yes,Yes,RK World Infocom Pvt Ltd,Yes
1,Tissues,Plain Paper Napkins,Normal Range,ORG-PN-NR-P8-800-VB,B00E3QVVQO,Tissue Paper Napkins Pack of 8 - 100 Pulls Eac...,Yes,Yes,400,340,Yes,Yes,Yes,RK World Infocom Pvt Ltd,Yes
2,Tissues,Printed Paper Napkins,Luxuria,ORG-PPN-LX-P6-300-VB,B00W160BGY,Tissue Paper Napkins Pack of 6 - 50 Pulls Each...,Yes,Yes,540,459,Yes,Yes,Yes,RK World Infocom Pvt Ltd,Yes
3,Tissues,Facial Tissues - Mono,So Soft,ORG-FTM-SS-P3-600-HB,B00W1EGH28,"Facial Tissue Pack of 3 - 200 Pulls Each, 2 Ply",Yes,Yes,555,471.75,Yes,Yes,Yes,RK World Infocom Pvt Ltd,Yes
4,Tissues,Toilet Tissues,Normal Range,ORG-TT-NR-P12-1920-HB,B00W1G5KQU,"Toilet Tissue Paper Roll, Pack of 12, 160 Pull...",Yes,Yes,570,484.5,Yes,Yes,Yes,RK World Infocom Pvt Ltd,Yes

In [4]:
df_amazon_scrapped.head()

,Unnamed: 0,ASIN,Pincode,Title Length,MRP,Live Price,Availability,Deal Tag,Title,Bullet Points,Count of Catalog Images,Videos in Catalog,EDD,EDD_Fresh,Number of Variations,3 Star Ratings,2 Star Ratings,1 Star Ratings,Total Ratings,Ratings,Sub-Category BSR,Category BSR,Sold By,Description,BXGY,A+,SNS,Coupon,Number of Other Sellers
0,0,B0C8NPK4RD,400013,126.0,918,"â‚¹1,080",Yes,No,Origami Good Karma 2 Ply Facial Tissue Box | C...,4.0,3.0,0.0,1.0,NaN,0.0,17%,11%,10%,12 ratings,3.7,#340,"#97,610",Clicktech Retail Private Ltd,Yes,Yes,No,Yes,No,NaN
1,1,B0DM1RRNS5,400013,132.0,810,â‚¹890,Yes,No,Good Karma Compostable & Eco Friendly Garbage ...,1.0,6.0,0.0,4.0,NaN,0.0,0%,0%,0%,NaN,NaN,"#2,763","#1,531,224",origami So soft,Yes,No,No,NaN,No,NaN
2,2,B079YYQZJD,400013,86.0,"2,600","â‚¹2,850",Yes,No,Origami 3 Ply Toilet Tissue Paper Roll - Pack ...,3.0,7.0,0.0,1.0,NaN,0.0,44%,0%,0%,3 ratings,4.1,#787,"#218,147",origami So soft,No,No,Yes,NaN,No,NaN
3,3,B0CM3CG9S9,400013,27.0,NaN,NaN,Yes,No,Origami Baby Wipes Pack (3),4.0,1.0,0.0,NaN,NaN,0.0,0%,0%,0%,NaN,NaN,NaN,NaN,NaN,Yes,No,No,NaN,No,NaN
4,4,B0CDGJ8WGV,400013,148.0,379,â‚¹640,Yes,No,Origami Leakproof Sanitary Disposal Bags Pack ...,4.0,4.0,0.0,1.0,NaN,6.0,4%,2%,3%,478 ratings,4.5,#18,"#1,388",RK World Infocom Pvt Ltd,Yes,Yes,No,Yes,No,2.0

In [5]:
df_amazon_scrapped['EDD'] = df_amazon_scrapped['EDD'].fillna(df_amazon_scrapped['EDD_Fresh'])
df_mapping['Sub-category'] = df_mapping['Category']
df_amazon_scrapped_v2 = df_amazon_scrapped.rename(columns={'Live Price':'MRP','MRP':'Live Price'})

In [6]:
df_amazon_scrapped_v2.head()

,Unnamed: 0,ASIN,Pincode,Title Length,Live Price,MRP,Availability,Deal Tag,Title,Bullet Points,Count of Catalog Images,Videos in Catalog,EDD,EDD_Fresh,Number of Variations,3 Star Ratings,2 Star Ratings,1 Star Ratings,Total Ratings,Ratings,Sub-Category BSR,Category BSR,Sold By,Description,BXGY,A+,SNS,Coupon,Number of Other Sellers
0,0,B0C8NPK4RD,400013,126.0,918,"â‚¹1,080",Yes,No,Origami Good Karma 2 Ply Facial Tissue Box | C...,4.0,3.0,0.0,1.0,NaN,0.0,17%,11%,10%,12 ratings,3.7,#340,"#97,610",Clicktech Retail Private Ltd,Yes,Yes,No,Yes,No,NaN
1,1,B0DM1RRNS5,400013,132.0,810,â‚¹890,Yes,No,Good Karma Compostable & Eco Friendly Garbage ...,1.0,6.0,0.0,4.0,NaN,0.0,0%,0%,0%,NaN,NaN,"#2,763","#1,531,224",origami So soft,Yes,No,No,NaN,No,NaN
2,2,B079YYQZJD,400013,86.0,"2,600","â‚¹2,850",Yes,No,Origami 3 Ply Toilet Tissue Paper Roll - Pack ...,3.0,7.0,0.0,1.0,NaN,0.0,44%,0%,0%,3 ratings,4.1,#787,"#218,147",origami So soft,No,No,Yes,NaN,No,NaN
3,3,B0CM3CG9S9,400013,27.0,NaN,NaN,Yes,No,Origami Baby Wipes Pack (3),4.0,1.0,0.0,NaN,NaN,0.0,0%,0%,0%,NaN,NaN,NaN,NaN,NaN,Yes,No,No,NaN,No,NaN
4,4,B0CDGJ8WGV,400013,148.0,379,â‚¹640,Yes,No,Origami Leakproof Sanitary Disposal Bags Pack ...,4.0,4.0,0.0,1.0,NaN,6.0,4%,2%,3%,478 ratings,4.5,#18,"#1,388",RK World Infocom Pvt Ltd,Yes,Yes,No,Yes,No,2.0

In [7]:
grouped_df = df_amazon_scrapped_v2.groupby('ASIN').agg(lambda x: x.dropna().sample(1).iloc[0] if not x.dropna().empty else np.nan)
grouped_df = grouped_df.reset_index()

### EDD vs pincodes

In [8]:
df_amazon_scrapped_400013 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 400013][['ASIN','EDD']]
df_amazon_scrapped_400013.columns = ['ASIN','EDD_400013']
df_amazon_scrapped_600005 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 600005][['ASIN','EDD']]
df_amazon_scrapped_600005.columns = ['ASIN','EDD_600005']
df_amazon_scrapped_122102 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 122102][['ASIN','EDD']]
df_amazon_scrapped_122102.columns = ['ASIN','EDD_122102']
df_amazon_scrapped_700016 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 700016][['ASIN','EDD']]
df_amazon_scrapped_700016.columns = ['ASIN','EDD_700016']
df_amazon_scrapped_560068 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 560068][['ASIN','EDD']]
df_amazon_scrapped_560068.columns = ['ASIN','EDD_560068']

grouped_df = grouped_df.merge(df_amazon_scrapped_400013,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_600005,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_122102,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_700016,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_560068,how='left',on='ASIN')

### Sold By vs pincodes

In [9]:
df_amazon_scrapped_400013 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 400013][['ASIN','Sold By']]
df_amazon_scrapped_400013.columns = ['ASIN','Sold By_400013']
df_amazon_scrapped_600005 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 600005][['ASIN','Sold By']]
df_amazon_scrapped_600005.columns = ['ASIN','Sold By_600005']
df_amazon_scrapped_122102 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 122102][['ASIN','Sold By']]
df_amazon_scrapped_122102.columns = ['ASIN','Sold By_122102']
df_amazon_scrapped_700016 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 700016][['ASIN','Sold By']]
df_amazon_scrapped_700016.columns = ['ASIN','Sold By_700016']
df_amazon_scrapped_560068 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 560068][['ASIN','Sold By']]
df_amazon_scrapped_560068.columns = ['ASIN','Sold By_560068']

grouped_df = grouped_df.merge(df_amazon_scrapped_400013,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_600005,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_122102,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_700016,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_560068,how='left',on='ASIN')

### Live Price vs pincodes

In [10]:
df_amazon_scrapped_400013 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 400013][['ASIN','Live Price']]
df_amazon_scrapped_400013.columns = ['ASIN','Live Price_400013']
df_amazon_scrapped_600005 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 600005][['ASIN','Live Price']]
df_amazon_scrapped_600005.columns = ['ASIN','Live Price_600005']
df_amazon_scrapped_122102 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 122102][['ASIN','Live Price']]
df_amazon_scrapped_122102.columns = ['ASIN','Live Price_122102']
df_amazon_scrapped_700016 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 700016][['ASIN','Live Price']]
df_amazon_scrapped_700016.columns = ['ASIN','Live Price_700016']
df_amazon_scrapped_560068 = df_amazon_scrapped_v2[df_amazon_scrapped_v2['Pincode'] == 560068][['ASIN','Live Price']]
df_amazon_scrapped_560068.columns = ['ASIN','Live Price_560068']

grouped_df = grouped_df.merge(df_amazon_scrapped_400013,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_600005,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_122102,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_700016,how='left',on='ASIN')
grouped_df = grouped_df.merge(df_amazon_scrapped_560068,how='left',on='ASIN')

In [11]:
grouped_df.head()

,ASIN,Unnamed: 0,Pincode,Title Length,Live Price,MRP,Availability,Deal Tag,Title,Bullet Points,Count of Catalog Images,Videos in Catalog,EDD,EDD_Fresh,Number of Variations,3 Star Ratings,2 Star Ratings,1 Star Ratings,Total Ratings,Ratings,Sub-Category BSR,Category BSR,Sold By,Description,BXGY,A+,SNS,Coupon,Number of Other Sellers,EDD_400013,EDD_600005,EDD_122102,EDD_700016,EDD_560068,Sold By_400013,Sold By_600005,Sold By_122102,Sold By_700016,Sold By_560068,Live Price_400013,Live Price_600005,Live Price_122102,Live Price_700016,Live Price_560068
0,B00E3QVP06,507,122102,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B00E3QVVQO,656,700016,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B00E3QWLOU,808,122102,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B00W160BGY,1103,122102,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B00W16IZLC,60,600005,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_input = df_mapping[["SKU","ASIN","Generic Title","Sub-category","MRP","Price Rule","Coupon Rule","SNS Rule","BXGY Rule",'Buy Box Rule',"Hygiene Tracking"]]
df_input = df_input[df_input['Hygiene Tracking'] == 'Yes']

In [13]:
grouped_df['EDD_400013'] += 1
grouped_df['EDD_600005'] += 1
grouped_df['EDD_122102'] += 1
grouped_df['EDD_700016'] += 1
grouped_df['EDD_560068'] += 1
grouped_df['EDD'] += 1

grouped_df['EDD_400013_Score'] = (grouped_df['EDD_400013'] <= 2).astype("int")
grouped_df['EDD_600005_Score'] = (grouped_df['EDD_600005'] <= 2).astype("int")
grouped_df['EDD_122102_Score'] = (grouped_df['EDD_122102'] <= 2).astype("int")
grouped_df['EDD_700016_Score'] = (grouped_df['EDD_700016'] <= 2).astype("int")
grouped_df['EDD_560068_Score'] = (grouped_df['EDD_560068'] <= 2).astype("int")

grouped_df['EDD'] = (grouped_df['EDD_400013_Score'] + grouped_df['EDD_600005_Score'] + grouped_df['EDD_122102_Score'] + 
                     grouped_df['EDD_700016_Score'] + grouped_df['EDD_560068_Score'])*20

In [14]:
grouped_df = grouped_df.rename(columns={'Bullets_Count':'Bullet Points'})
df_amazon_scrapped = grouped_df[["ASIN","Live Price","Coupon","SNS","BXGY","Availability",'Deal Tag',
                                 "EDD_400013","EDD_600005","EDD_122102","EDD_700016","EDD_560068","EDD",
                                 "Sold By_400013","Sold By_600005","Sold By_122102","Sold By_700016","Sold By_560068",
                                 "Live Price_400013","Live Price_600005","Live Price_122102","Live Price_700016","Live Price_560068",
                                 "3 Star Ratings","2 Star Ratings","1 Star Ratings","Total Ratings",
                                 "Ratings","Sub-Category BSR","Category BSR","Number of Other Sellers",
                                 "Title Length","Bullet Points","Videos in Catalog","Count of Catalog Images","A+"]]


column_mapping = {
    "Coupon": "Live Coupon",
    "SNS": "Live SNS",
    "BXGY": "Live BXGY",
    "Sold By": "Sold by",
    "Bullet Points": "Bullet Point Count",
    "Count of Catalog Images": "Images Count",
    "Videos in Catalog":"Videos Count"
       
}

# Rename columns
df_amazon_scrapped = df_amazon_scrapped.rename(columns=column_mapping)
df_input = df_input.merge(df_amazon_scrapped,on='ASIN',how='left')
df_input = df_input[df_input['ASIN'].isin(df_amazon_scrapped['ASIN'].unique())]

### Live Price Hygeine

In [15]:
df_input['Live Price_400013'] = df_input['Live Price_400013'].str.strip("â‚¹").str.replace(",","")
df_input['Live Price_600005'] = df_input['Live Price_600005'].str.strip("â‚¹").str.replace(",","")
df_input['Live Price_122102'] = df_input['Live Price_122102'].str.strip("â‚¹").str.replace(",","")
df_input['Live Price_700016'] = df_input['Live Price_700016'].str.strip("â‚¹").str.replace(",","")
df_input['Live Price_560068'] = df_input['Live Price_560068'].str.strip("â‚¹").str.replace(",","")

df_input['Price Rule'] = df_input['Price Rule'].astype('float')

df_input['Live Price_400013'] = df_input['Live Price_400013'].astype('float')
df_input['Live Price_600005'] = df_input['Live Price_600005'].astype('float')
df_input['Live Price_122102'] = df_input['Live Price_122102'].astype('float')
df_input['Live Price_700016'] = df_input['Live Price_700016'].astype('float')
df_input['Live Price_560068'] = df_input['Live Price_560068'].astype('float')

df_input['Live Price_400013_Score'] = (df_input['Live Price_400013'] == df_input['Price Rule']).astype("int", errors='ignore')
df_input['Live Price_600005_Score'] = (df_input['Live Price_600005'] == df_input['Price Rule']).astype("int", errors='ignore')
df_input['Live Price_122102_Score'] = (df_input['Live Price_122102'] == df_input['Price Rule']).astype("int", errors='ignore')
df_input['Live Price_700016_Score'] = (df_input['Live Price_700016'] == df_input['Price Rule']).astype("int", errors='ignore')
df_input['Live Price_560068_Score'] = (df_input['Live Price_560068'] == df_input['Price Rule']).astype("int", errors='ignore')

df_input['Price'] = (df_input['Live Price_400013_Score']+df_input['Live Price_600005_Score']+
                     df_input['Live Price_122102_Score']+df_input['Live Price_700016_Score']+df_input['Live Price_560068_Score'])*20

### Sold By Hygeine

In [16]:
df_input['Sold By_400013_Score'] = (df_input['Sold By_400013'] == df_input['Buy Box Rule']).astype("int")
df_input['Sold By_600005_Score'] = (df_input['Sold By_600005'] == df_input['Buy Box Rule']).astype("int")
df_input['Sold By_122102_Score'] = (df_input['Sold By_122102'] == df_input['Buy Box Rule']).astype("int")
df_input['Sold By_700016_Score'] = (df_input['Sold By_700016'] == df_input['Buy Box Rule']).astype("int")
df_input['Sold By_560068_Score'] = (df_input['Sold By_560068'] == df_input['Buy Box Rule']).astype("int")

df_input['Sold By'] = (df_input['Sold By_400013_Score']+df_input['Sold By_600005_Score']+
                       df_input['Sold By_122102_Score']+df_input['Sold By_700016_Score']+df_input['Sold By_560068_Score'])*20

In [17]:
df_input['Coupon Validation'] = df_input['Live Coupon'] == df_input['Coupon Rule']
df_input['SNS Validation'] = df_input['Live SNS'] == df_input['SNS Rule']
df_input['BXGY Validation'] = df_input['Live BXGY'] == df_input['BXGY Rule']

df_input["Catalog Score"] = (df_input['Ratings'] >= 4).astype(int) + (df_input['Title Length'] >= 180).astype(int) + (df_input['Bullet Point Count'] > 5).astype(int) + (df_input['Images Count'] >= 7).astype(int) + (df_input['A+'] == 'Yes').astype(int)
df_input["Catalog Score"] = df_input["Catalog Score"]*20
df_input["Date"] = datetime.today().strftime('%Y-%m-%d')
df_input['Total Ratings'] = (
    df_input['Total Ratings']
    .str.replace(',', '', regex=True)  # Remove commas
    .str.extract(r'(\d+)')  # Extract numeric values
    .astype(float)  # Convert to float
)

In [18]:
def calculate_hygiene_metrics(df):
    """
    Calculate hygiene metrics for each row in the dataset
    
    Parameters:
    df (pandas.DataFrame): DataFrame containing the required columns
    
    Returns:
    pandas.DataFrame: Original DataFrame with additional hygiene metrics columns
    """
    # Create a copy of the DataFrame to avoid modifying the original
    result_df = df.copy()
    
    # 1. Activation Hygiene (100% if both validations are True, 0% if either is False)
    result_df['Activation_Hygiene'] = ((result_df['SNS Validation'] == True) & 
                                     (result_df['BXGY Validation'] == True)) * 100
    
    
    # 2. EDD Hygiene (100% if EDD â‰¤ 2, 0% if EDD > 2), Price Hygiene, Buy Box_Hygiene
    result_df['EDD_Hygiene'] = result_df['EDD']
    result_df['Price_Hygiene'] = result_df['Price']
    result_df['Buy Box_Hygiene'] = result_df['Sold By']
    
    
    # 3. Catalog Hygiene (use raw Catalog Score for each row)
    result_df['Catalog_Hygiene'] = result_df['Catalog Score']
    
    # 4. Rating Hygiene (divide by 5 and multiply by 100 for percentage)
    result_df['Rating_Hygiene'] = (result_df['Ratings'] / 5) * 100
    
    # 5. Availability Hygiene (100% if Available, 0% if Not Available)
    result_df['Availability_Hygiene'] = (result_df['Availability'] == 'Yes') * 100
    
    # 6. Deal Hygiene (100% if Coupon Validation is True, 0% if False)
    result_df['Deal_Hygiene'] = result_df['Coupon Validation'] * 100
    
    # 7. Overall Brand Score
    result_df['Overall_Brand_Score'] = (
        (result_df['Price_Hygiene'].fillna(0) * 0.1) +
        (result_df['Activation_Hygiene'].fillna(0) * 0.05) +
        (result_df['Deal_Hygiene'].fillna(0) * 0.05) +
        (result_df['Availability_Hygiene'].fillna(0) * 0.2) +
        (result_df['EDD_Hygiene'].fillna(0) * 0.1) +
        (result_df['Rating_Hygiene'].fillna(0) * 0.2) +
        (result_df['Catalog_Hygiene'].fillna(0) * 0.2)+
        (result_df['Buy Box_Hygiene'].fillna(0) * 0.1)
    )   # Divide by 100 to get final percentage
     
    #Need to change the overall score calculation
    return result_df

df_input = calculate_hygiene_metrics(df_input)

In [19]:
df_input.columns

Index(['SKU', 'ASIN', 'Generic Title', 'Sub-category', 'MRP', 'Price Rule',
       'Coupon Rule', 'SNS Rule', 'BXGY Rule', 'Buy Box Rule',
       'Hygiene Tracking', 'Live Price', 'Live Coupon', 'Live SNS',
       'Live BXGY', 'Availability', 'Deal Tag', 'EDD_400013', 'EDD_600005',
       'EDD_122102', 'EDD_700016', 'EDD_560068', 'EDD', 'Sold By_400013',
       'Sold By_600005', 'Sold By_122102', 'Sold By_700016', 'Sold By_560068',
       'Live Price_400013', 'Live Price_600005', 'Live Price_122102',
       'Live Price_700016', 'Live Price_560068', '3 Star Ratings',
       '2 Star Ratings', '1 Star Ratings', 'Total Ratings', 'Ratings',
       'Sub-Category BSR', 'Category BSR', 'Number of Other Sellers',
       'Title Length', 'Bullet Point Count', 'Videos Count', 'Images Count',
       'A+', 'Live Price_400013_Score', 'Live Price_600005_Score',
       'Live Price_122102_Score', 'Live Price_700016_Score',
       'Live Price_560068_Score', 'Price', 'Sold By_400013_Score',
       'Sold By_600005_Score', 'Sold By_122102_Score', 'Sold By_700016_Score',
       'Sold By_560068_Score', 'Sold By', 'Coupon Validation',
       'SNS Validation', 'BXGY Validation', 'Catalog Score', 'Date',
       'Activation_Hygiene', 'EDD_Hygiene', 'Price_Hygiene', 'Buy Box_Hygiene',
       'Catalog_Hygiene', 'Rating_Hygiene', 'Availability_Hygiene',
       'Deal_Hygiene', 'Overall_Brand_Score'],
      dtype='object')

In [21]:
df_input = df_input[["Date","SKU","ASIN","Generic Title","Sub-category",
                     "MRP","Price Rule","Live Price","Live Price_400013","Live Price_600005","Live Price_122102","Live Price_700016","Live Price_560068","Price_Hygiene",
                     "Coupon Rule","Live Coupon","Coupon Validation","Deal_Hygiene","SNS Rule","Live SNS","SNS Validation",
                     "BXGY Rule","Live BXGY","BXGY Validation","Activation_Hygiene","Availability","Availability_Hygiene","Deal Tag",
                     "EDD_400013","EDD_600005","EDD_122102","EDD_700016","EDD_560068","EDD_Hygiene",
                     "Sold By_400013","Sold By_600005","Sold By_122102","Sold By_700016","Sold By_560068","Buy Box_Hygiene", "Buy Box Rule",
                     "3 Star Ratings","2 Star Ratings","1 Star Ratings","Total Ratings","Ratings","Rating_Hygiene",
                     "Sub-Category BSR","Category BSR","Number of Other Sellers","Title Length","Bullet Point Count",
                     "Videos Count","Images Count","A+","Catalog_Hygiene","Overall_Brand_Score"]]
df_input = df_input.rename(columns={"SKU": "SKU Code"})

In [22]:
df_input.to_excel("pipeline_output_11_03_25_Origmai_transformed.xlsx", index = False)